openapi: 3.0.0
info:
  version: 1.0.0
  title: Respondent Profile Survey API
  description: Respondent Profile Survey API
  termsOfService: http://swagger.io/terms/
  contact:
    name: API Team
    email: apiteam@eoc.io
    url: http://eoc.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://eoc-respondent-optional-info.infra-workers.workers.dev/
  - url: http://localhost:8787
paths:
  /question-statistic:
    get:
      tags:
        - QuestionStatistic
      summary: Returns all QuestionStatistic from the system that the user has access to
      description: Returns all QuestionStatistic from the system that the user has access to
      operationId: findQuestionStatistic
      parameters:
        - schema:
            type: number
            description: Page number
          required: true
          description: Page number
          name: page
          in: query
        - schema:
            type: boolean
            description: Filter by completed flag
          required: false
          description: Filter by completed flag
          name: isCompleted
          in: query
      responses:
        '200':
          description: QuestionStatistic response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QuestionStatistic'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - QuestionStatistic
      summary: Creates / Update QuestionStatistic in the store. 
      description: Creates/ Update QuestionStatistic in the store. 
      operationId: addQuestionStatistic
      requestBody:
        description: QuestionStatistic to add / update to the store
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/QuestionStatistic'
      responses:
        '200':
          description: OK
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /question-statistic/{profileSurveyStatisticId}:
    post:
      tags:
        - QuestionStatistic
      summary: Returns profile survey question statistic from the system that the user has access to
      description: Returns profile survey question statistic from the system that the user has access to
      operationId: findQuestionStatisticByProfileSurveyStatisticIdAndQuestionStatisticFilter
      parameters:
        - schema:
            type: string
            description: Profile Survey Statistic Name Id
          required: true
          description: Profile Survey Statistic Name Id
          name: profileSurveyStatisticId
          in: path
      requestBody:
        description: QuestionStatistic filter
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/QuestionStatisticFilter'
      responses:
        '200':
          description: QuestionStatistic response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QuestionStatistic'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /suvery-index:
    post:
      tags:
        - RespondentProfileSurveyIndex
      summary: Creates a new RespondentProfileSurveyIndex in the store.  Duplicates are not allowed
      description: Creates a new RespondentProfileSurveyIndex in the store.  Duplicates are not allowed
      operationId: addRespondentProfileSurveyIndex
      requestBody:
        description: RespondentProfileSurveyIndex to add to the store
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewRespondentProfileSurveyIndex'
      responses:
        '200':
          description: RespondentProfileSurveyIndex response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespondentProfileSurveyIndex'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /suvery-index/{id}:
    get:
      tags:
        - RespondentProfileSurveyIndex
      summary: Returns a RespondentProfileSurveyIndex based on a single ID
      description: Returns a RespondentProfileSurveyIndex based on a single ID
      operationId: findRespondentProfileSurveyIndexById
      parameters:
        - name: id
          in: path
          description: ID of RespondentProfileSurveyIndex to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: RespondentProfileSurveyIndex response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespondentProfileSurveyIndex'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - RespondentProfileSurveyIndex
      summary: Update RespondentProfileSurveyIndex in the store based on a single ID
      description: Update RespondentProfileSurveyIndex in the store based on a single ID
      operationId: updateRespondentProfileSurveyIndex
      parameters:
        - name: id
          in: path
          description: ID of RespondentProfileSurveyIndex to update
          required: true
          schema:
            type: string
      requestBody:
        description: RespondentProfileSurveyIndex to update to the store
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewRespondentProfileSurveyIndex'
      responses:
        '200':
          description: RespondentProfileSurveyIndex response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespondentProfileSurveyIndex'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /suvery-info:
    get:
      tags:
        - RespondentProfileSurvey
      summary: Returns all RespondentProfileSurvey from the system that the user has access to
      description: Returns all RespondentProfileSurvey from the system that the user has access to
      operationId: findRespondentProfileSurvey
      parameters:
        - schema:
            type: number
            description: Page number
          required: true
          description: Page number
          name: page
          in: query
        - schema:
            type: boolean
            description: Filter by completed flag
          required: false
          description: Filter by completed flag
          name: isCompleted
          in: query
      responses:
        '200':
          description: RespondentProfileSurvey response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RespondentProfileSurvey'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - RespondentProfileSurvey
      summary: Creates a new RespondentProfileSurvey in the store.  Duplicates are not allowed
      description: Creates a new RespondentProfileSurvey in the store.  Duplicates are not allowed
      operationId: addRespondentProfileSurvey
      requestBody:
        description: RespondentProfileSurvey to add to the store
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewRespondentProfileSurvey'
      responses:
        '200':
          description: RespondentProfileSurvey response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespondentProfileSurvey'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /suvery-info/{id}:
    get:
      tags:
        - RespondentProfileSurvey
      summary: Returns a RespondentProfileSurvey based on a single ID
      description: Returns a RespondentProfileSurvey based on a single ID
      operationId: findRespondentProfileSurveyById
      parameters:
        - name: id
          in: path
          description: ID of RespondentProfileSurvey to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: RespondentProfileSurvey response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespondentProfileSurvey'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - RespondentProfileSurvey
      summary: Update RespondentProfileSurvey in the store based on a single ID
      description: Update RespondentProfileSurvey in the store based on a single ID
      operationId: updateRespondentProfileSurvey
      parameters:
        - name: id
          in: path
          description: ID of RespondentProfileSurvey to update
          required: true
          schema:
            type: string
      requestBody:
        description: RespondentProfileSurvey to add to the store
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewRespondentProfileSurvey'
      responses:
        '200':
          description: RespondentBasicData response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespondentProfileSurvey'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - RespondentProfileSurvey
      summary: deletes a single RespondentProfileSurvey based on the ID supplied
      description: deletes a single RespondentProfileSurvey based on the ID supplied
      operationId: deleteRespondentProfileSurvey
      parameters:
        - name: id
          in: path
          description: ID of RespondentProfileSurvey to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: RespondentProfileSurvey deleted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  schemas:
    NewRespondentProfileSurveyIndex:
      type: object
      properties:
        currentSurveyId:
          type: string
        lastSurveyId:
          type: string
    RespondentProfileSurveyIndex:
      allOf:
        - $ref: '#/components/schemas/NewRespondentProfileSurveyIndex'      
        - type: object
          required:
            - othentId
          properties:
            othentId:
              type: string  
    RespondentProfileSurvey:
      allOf:
        - $ref: '#/components/schemas/NewRespondentProfileSurvey'
        - type: object
          required:
            - id
          properties:
            id:
              type: string
    NewRespondentProfileSurvey:
      type: object
      properties:
        type:
          type: string    
        respondentOthentSub:
          type: string
        targetGroups: 
          type: array
          items:
            $ref: '#/components/schemas/TargetGroup'
    TargetGroup:
      type: object
      properties:
        age:
          type: integer
          format: int32
        gender:
          type: string
        country:
          type: string
        surveyData:
          type: array
          items:
            $ref: '#/components/schemas/Question'
    Question:
      type: object
      required:
        - question
        - questionType
      properties:
        question:
          type: string
        questionType:
          type: string  
        category:
          type: string
        possibleAnswers:
          type: array
          items:
            type: string
        answers:
          type: array
          items:
            type: string
    QuestionStatistic:
      type: object
      required:
        - profileSurveyStatisticId
        - question
        - answer
        - dateOfBirth
        - country
        - gender
      properties:
        profileSurveyStatisticId: 
          type: string
        question: 
          type: string
        answer: 
          type: string
        dateOfBirth:
          type: string
          format: date
        country:
          type: string
        gender: 
          type: string  
        count: 
          type: number
          format: int32
    QuestionStatisticFilter:
      type: object
      required:
        - question
        - country
      properties:
        question: 
          type: string
        answer: 
          type: string
        minAge:
          type: number
          format: int32
        maxAge:
          type: number
          format: int32
        country:
          type: string
        gender: 
          type: string  
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
security:
  - bearerAuth: [] 